### ISSUE TITLE
pytorch  runtime error, version==0.4.0

### ISSUE THREAD

**Issue by luweishuang** [mojesty/professor_forcing#1]
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    main()
  File "train.py", line 108, in main
    for idx, batch in enumerate(lmloader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 115, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 35 and 34 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMath.c:3586

**Comment by mojesty** [comment]
I'll reply about this problem in 3 days, but are you really using python 2.7?

**Comment by mojesty** [comment]
Well, I've updated the code and now the training _without_ `adversarial` option should go fine. 
If you experience some problems, provide further detail about your environment and data.
Adversarial training is still under development, if you like to contribute, let me know.
